Update phppsinfo.php with litespeed support
PrestaShop/php-ps-info pull request #26
Opened 2023-01-16 11:49 UTC by Vudubond

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Update phppsinfo.php with litespeed support
| Type?             |  improvement
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes {paste the issue here}.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Upload script on Litespeed server shows Apache Module (low performance)

2023-01-25 12:44 UTC, 0x346e3730 requested changes
Could you please fill out your PR description correctly ? Thank you !

2023-01-27 06:53 UTC, Vudubond commented
Hello,

PR edited. Please check.

2023-03-31 15:07 UTC, kpodemski submitted a review, later dismissed
Sorry for the late reply @Vudubond. I think there are some issues with code formatting. You should use 4 spaces. Maybe it could also say "Better performance", instead "Super performance".

2023-05-26 06:52 UTC, kpodemski commented on phppsinfo.php
> +       $data = [
```suggestion
        $data = [
```

2023-05-26 06:53 UTC, kpodemski commented on phppsinfo.php
> +                (strpos(PHP_SAPI, 'litespeed') !== false ? '<span style="color: green">Litespeed (Super performance)</span>' : 'Apache Module (low performance)')
```suggestion
                (strpos(PHP_SAPI, 'litespeed') !== false ? '<span style="color: green">Litespeed (Better performance)</span>' : 'Apache Module (low performance)')
```

2023-07-26 08:17 UTC, Vudubond commented
Requested Changes have been updated. Please check.

2024-06-13 14:31 UTC, matks approved these changes

2024-06-13 14:31 UTC, matks commented
Tested and validated? Thank you @Vudubond and apologies for late feedback

2024-06-13 14:32 UTC, merged